version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://reportfocusnews.com
      - NEXT_PUBLIC_WORDPRESS_API_URL=https://backend.reportfocusnews.com/graphql
    restart: unless-stopped